name: Lambda

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Installing AWS cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      - name: Build Maven
        run: mvn clean install

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 cp ./target/aws-lambda-0.0.1.zip s3://rk.csye6225.com/aws-lambda-0.0.1.zip

      - name: Run the lambda stack
        working-directory: ./lambda
        run: aws cloudformation create-stack --stack-name mylambdastack --template-body file://csye6225-infra-lambda.yaml --capabilities CAPABILITY_NAMED_IAM

#      - name: Update the lambda function
#        run: aws lambda update-function-code --function-name myLambda --s3-bucket rk.csye6225.com --s3-key aws-lambda-0.0.1.zip --region us-east-1





