name: Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Set Up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Launching Database on Docker
        run: |
          docker run --detach \--env MYSQL_ROOT_PASSWORD=user \--env MYSQL_USER=user \--env MYSQL_PASSWORD=user \--env MYSQL_DATABASE=mydatabase \--name mysql \--publish 3306:3306 mysql:8-oracle

      - name: Build Maven
        run: mvn clean install

      - name: Test
        run: mvn test -DskipTests=false

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Validate Packer
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ami.pkr.hcl
          working_directory: ami
        env:
          PACKER_LOG: 1 # enable debug log for packer
#
#      - name: Packer build
#        uses: hashicorp/packer-github-actions@master
#        with:
#          command: build
#          arguments: "-color=false -on-error=abort"
#          target: ami.pkr.hcl
#          working_directory: ami
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_PROFILE: ${{ secrets.AWS_PROFILE }}



